# Generated by Django 4.1.4 on 2022-12-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datacopleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
